language: node_js
node_js: 
  - "8.4"
  - "stable"

install: cd app && npm install
script: npm run build

# github pages setup
# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#   keep-history: true
#   on:
#     branch: master
#   local-dir: dist
#   target-branch: gh-pages

# github build branch setup
# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#   keep-history: true
#   on:
#     branch: master
#   local-dir: dist
#   target-branch: build